service: aws-node-esbuild-template
frameworkVersion: '3'

package:
  individually: true

plugins:
  - serverless-esbuild
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  httpApi:
    cors: true
  environment:
    NODE_OPTIONS: "--enable-source-maps"

params:
  default:
    esbuildMinify: true
    esbuildExclude:
      - aws-sdk
  local:
    esbuildMinify: false
    esbuildExclude: []

custom:
  stages:
    - local
    - dev
    - prod
  stage: ${opt:stage, 'dev'}
  esbuild:
    bundle: true
    minify: ${param:esbuildMinify}
    sourcemap: true
    keepNames: true
    watch:
      pattern: 
        - 'src/**/*.ts'
    exclude: ${param:esbuildExclude}

functions:
  status:
    handler: src/api/handler.handler
    events:
      - httpApi:
          path: /status
          method: get